language: node_js
node_js:
  - 11.11.0

script:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh $STAGING_IP_ADDRESS nginx_ssl_staging.conf
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh $STAGING_IP_ADDRESS nginx_ssl_staging.conf
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh $PRODUCTION_IP_ADDRESS nginx_ssl_prod.conf
    on:
      branch: master
